### ISSUE TITLE
[Bug] RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

### ISSUE THREAD

**Issue by Deathproof76** [vale46n1/immich_duplicate_finder#32]
Hi, thank you for this project, really cool idea!
I built the docker image and everything went fine up until 4000 of 40000 assets. 

![image](https://github.com/vale46n1/immich_duplicate_finder/assets/95944496/2bb7a716-98f9-4d18-98ea-43e9665499ec)

```
name: immich-duplicate-finder2
services:
  immich-duplicate-finder2:
    container_name: immich-duplicate-finder2
    hostname: immich-duplicate-finder2
    restart: unless-stopped
    volumes:
      - /mnt/Dockerspace/immich_duplicate_finder_test/db/settings.db:/immich_duplicate_finder/settings.db
      - /mnt/Dockerspace/immich_duplicate_finder_test/db/processed_assets.db:/immich_duplicate_finder/processed_assets.db
      - /mnt/Dockerspace/immich_duplicate_finder_test/db/duplicates.db:/immich_duplicate_finder/duplicates.db
      - /mnt/Dockerspace/immich_duplicate_finder_test/db/faiss_index.bin:/immich_duplicate_finder/faiss_index.bin
      - /mnt/Dockerspace/immich_duplicate_finder_test/db/metadata.npy:/immich_duplicate_finder/metadata.npy
      - /mnt/Dockerspace/immich_duplicate_finder_test/db/__pycache__:/immich_duplicate_finder/__pycache__
      - /mnt/Dockerspace/immich_duplicate_finder_test/cache:/root/.cache/torch/hub/checkpoints/
    ports:
      - 8502:8501
    build:
      dockerfile: './Dockerfile'
```
(btw: maybe move the databases to a separate folder for simpler mounting like https://github.com/vale46n1/immich_duplicate_finder/compare/main...ttlequals0:immich_duplicate_finder:main )

logs up until erroring out:

```
docker compose up
[+] Running 1/0
 ✔ Container immich-duplicate-finder2  Recreated                                                                                                                                                                        0.1s 
Attaching to immich-duplicate-finder2
immich-duplicate-finder2  | 
immich-duplicate-finder2  | Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
immich-duplicate-finder2  | 
immich-duplicate-finder2  | 
immich-duplicate-finder2  |   You can now view your Streamlit app in your browser.
immich-duplicate-finder2  | 
immich-duplicate-finder2  |   Network URL: http://#############
immich-duplicate-finder2  |   External URL: http://##############
immich-duplicate-finder2  | 
immich-duplicate-finder2  | Downloading: "https://download.pytorch.org/models/resnet152-f82ba261.pth" to /root/.cache/torch/hub/checkpoints/resnet152-f82ba261.pth
100.0%-duplicate-finder2  | 
immich-duplicate-finder2  | 2024-05-06 09:28:11.755 Uncaught app exception
immich-duplicate-finder2  | Traceback (most recent call last):
immich-duplicate-finder2  |   File "/usr/local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
immich-duplicate-finder2  |     exec(code, module.__dict__)
immich-duplicate-finder2  |   File "/immich_duplicate_finder/app.py", line 130, in <module>
immich-duplicate-finder2  |     main()
immich-duplicate-finder2  |   File "/immich_duplicate_finder/app.py", line 109, in main
immich-duplicate-finder2  |     calculateFaissIndex(
immich-duplicate-finder2  |   File "/immich_duplicate_finder/imageDuplicate.py", line 117, in calculateFaissIndex
immich-duplicate-finder2  |     status = update_faiss_index(immich_server_url,api_key, asset_id)
immich-duplicate-finder2  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder2  |   File "/immich_duplicate_finder/imageDuplicate.py", line 68, in update_faiss_index
immich-duplicate-finder2  |     features = extract_features(image)
immich-duplicate-finder2  |                ^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder2  |   File "/immich_duplicate_finder/imageDuplicate.py", line 35, in extract_features
immich-duplicate-finder2  |     image_tensor = transform(image).unsqueeze(0)  # Add batch dimension
immich-duplicate-finder2  |                    ^^^^^^^^^^^^^^^^
immich-duplicate-finder2  |   File "/usr/local/lib/python3.12/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
immich-duplicate-finder2  |     img = t(img)
immich-duplicate-finder2  |           ^^^^^^
immich-duplicate-finder2  |   File "/usr/local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
immich-duplicate-finder2  |     return self._call_impl(*args, **kwargs)
immich-duplicate-finder2  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder2  |   File "/usr/local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
immich-duplicate-finder2  |     return forward_call(*args, **kwargs)
immich-duplicate-finder2  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder2  |   File "/usr/local/lib/python3.12/site-packages/torchvision/transforms/transforms.py", line 277, in forward
immich-duplicate-finder2  |     return F.normalize(tensor, self.mean, self.std, self.inplace)
immich-duplicate-finder2  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder2  |   File "/usr/local/lib/python3.12/site-packages/torchvision/transforms/functional.py", line 349, in normalize
immich-duplicate-finder2  |     return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
immich-duplicate-finder2  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder2  |   File "/usr/local/lib/python3.12/site-packages/torchvision/transforms/_functional_tensor.py", line 926, in normalize
immich-duplicate-finder2  |     return tensor.sub_(mean).div_(std)
immich-duplicate-finder2  |            ^^^^^^^^^^^^^^^^^
immich-duplicate-finder2  | RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
```

I'm not a programmer but maybe it's related to an image with an alpha channel, RGBA instead of RGB? https://github.com/StoryMY/take-off-eyeglasses/issues/1#issuecomment-1122144903 https://github.com/christiansafka/img2vec/issues/31 https://github.com/christiansafka/img2vec/pull/37/commits/1cc7e273cc23822765be34aac90775b0fbb31252
